# PHP as Linux Web App on Azure
# Build, package and deploy your PHP project to Azure Linux Web App.
# Add steps that run tests and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
  - PRE-PROD

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: "app-azuredevops-groupegruau-pipelines-tst"

  # Web app name
  webAppName: "app-gruau-tst-saisie-heures"

  # Agent VM image name
  vmImageName: "ubuntu-20.04"

  # PHP version
  phpVersion: "8.3"

  # Environment name
  environmentName: "app-gruau-tst-saisie-heures"

stages:
- stage: Deploy
  displayName: "Deploy Web App"
  jobs:
  - deployment: DeploymentJob
    pool:
      vmImage: $(vmImageName)
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: 'Développements Symfony'  # Remplacez par le nom réel de votre projet Azure DevOps
              definition: 'Saisie Heures - CI - PRE-PROD & PROD'  # Nom exact du pipeline CI
              buildVersionToDownload: 'latest'
              downloadPath: '$(Pipeline.Workspace)'
          
          - script: ls $(Pipeline.Workspace)/drop
            displayName: "List contents of drop directory"
          
          - task: AzureRmWebAppDeployment@4
            displayName: "Déploiement de l'application"
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(azureSubscription)'
              appType: 'webAppLinux'
              WebAppName: '$(webAppName)'
              packageForLinux: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              StartupCommand: '/home/site/wwwroot/startup.sh'
              runtimeStack: 'PHP|$(phpVersion)'
