trigger:
- pipeline-pr

pool:
  vmImage: 'ubuntu-latest'
#
steps:
- script: |
    echo "Adresse IP publique de l'agent : $(curl -sS https://checkip.amazonaws.com)"
  displayName: 'Obtenir l adresse IP publique de l agent'
