trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    sudo apt update
    sudo apt install php
  displayName: 'Install PHP'

- script: |
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php composer-setup.php
    php -r "unlink('composer-setup.php');"
    mv composer.phar /usr/local/bin/composer
  displayName: 'Install Composer'

- script: |
    composer install
  displayName: 'Install Dependencies'

- script: |
    vendor/bin/phpunit
  displayName: 'Run PHPUnit Tests'