# PHP as Linux Web App on Azure
trigger:
  - Test-Slot

variables:
  azureSubscription: "app-azuredevops-groupegruau-pipelines-prd"
  azureTstSubscription: "app-azuredevops-groupegruau-pipelines-tst"
  webAppName: "app-gruau-prd-test-slot"
  vmImageName: "ubuntu-latest"
  environmentName: "app-gruau-prd-test-slot"
  rgName: "rg-prd-webapps"
  slotName: "preprod"
  rootFolder: $(System.DefaultWorkingDirectory)

stages:
  - stage: Build
    displayName: Build stage
    variables:
      phpVersion: "8.2"
    jobs:
      - job: BuildJob
        pool:
          vmImage: $(vmImageName)
        steps:
          - script: |
              sudo update-alternatives --set php /usr/bin/php$(phpVersion)
              sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
              sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
              sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
              sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
              php -version
            displayName: "Use PHP version $(phpVersion)"

          # Utiliser le cache Composer
          - task: Cache@2
            inputs:
              key: 'composer | "$(Agent.OS)" | composer.lock'
              restoreKeys: 'composer | "$(Agent.OS)"'
              path: '~/.composer/cache'
            displayName: "Cache Composer"

          - script: composer install --no-ansi --no-interaction --no-progress --prefer-dist --no-scripts
            displayName: "Composer install"

          # Utiliser le cache npm pour accélérer les installations
          - task: Cache@2
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: 'npm | "$(Agent.OS)"'
              path: '$(rootFolder)/node_modules'
            displayName: "Cache npm"

          - script: npm ci
            displayName: "Run npm install"

          - script: npm run build
            displayName: "Build JS assets"

          - script: php bin/console cache:clear --no-warmup
            displayName: "Clear cache"

          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(rootFolder)"
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            displayName: "Upload package"
            artifact: drop

  - stage: Deploy
    displayName: "Deploy Web App"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeploymentJob
        pool:
          vmImage: $(vmImageName)
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
              - task: AzureKeyVault@2
                displayName: "Récupération des secrets du Key Vault"
                inputs:
                  azureSubscription: "$(azureTstSubscription)"
                  KeyVaultName: "kv-gruau-tst"
                  SecretsFilter: "*"

              - task: AzureCLI@2
                displayName: "Configuration des variables d'environnement du Slot"
                inputs:
                  azureSubscription: '$(azureSubscription)'
                  scriptType: 'pscore'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    az webapp config appsettings set --name $(webAppName) --resource-group $(rgName) --slot $(slotName) --settings \
                    WEBSITE_RUN_FROM_PACKAGE=1 \
                    APP_ENV=prod \
                    APP_DEBUG=env \
                    DATABASE_HOST=$(saisie-heures-tst-dbHost) \
                    DATABASE_NAME=$(saisie-heures-tst-dbName) \
                    DATABASE_PASSWORD=$(saisie-heures-tst-dbPassword) \
                    DATABASE_PORT=$(saisie-heures-tst-dbPort) \
                    DATABASE_USER=$(saisie-heures-tst-dbUser) \
                    SECRET_KEY=$(saisie-heures-tst-appSecret)

              - task: AzureCLI@2
                displayName: "Déploiement rapide avec ZIP Deploy"
                inputs:
                  azureSubscription: '$(azureSubscription)'
                  scriptType: 'pscore'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    az webapp deployment source config-zip --resource-group $(rgName) --name $(webAppName) --slot $(slotName) --src "$(Pipeline.Workspace)/drop/$(Build.BuildId).zip"
