services:

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: saisieheures-nginx
    depends_on:
      - php
    labels:
      - traefik.enable=${TRAEFIK:-''}
      - traefik.http.routers.saisieheures.rule=Host(`${SERVICE_URL:-''}`)
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - APP_DEBUG=${APP_DEBUG:-''}
        - APP_ENV=${APP_ENV:-''}
        - APP_SECRET=${APP_SECRET:-''}
        - COMPOSER_NO_DEV=${COMPOSER_NO_DEV:-''}
        - DATABASE_HOST=${DATABASE_HOST:-''}
        - DATABASE_NAME=${DATABASE_NAME:-''}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD:-''}
        - DATABASE_PORT=${DATABASE_PORT:-''}
        - DATABASE_USER=${DATABASE_USER:-''}
        - MAILER_DSN=${MAILER_DSN:-''}
        - PHP_INI_ENV=${PHP_INI_ENV:-''}
    container_name: saisieheures-php
    restart: unless-stopped
