services:
  
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: saisieHeures
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gruau-local_mynetgruau

networks:
    gruau-local_mynetgruau:

volumes:
  postgres_data: