services:

  nginx:
    networks:
      - gruau-local_mynetgruau
    volumes:
      - ./app/public:/var/www/html/public

  php:
    networks:
      - gruau-local_mynetgruau
    volumes:
      - ./app:/var/www/html

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: helloworld-node
    networks:
      - gruau-local_mynetgruau
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html

networks:
    gruau-local_mynetgruau:
        external: true



