services:
  
  db:
    image: postgres:16.8
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gruau-local_mynetgruau

networks:
    gruau-local_mynetgruau:

volumes:
  postgres_data: