<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240304153455 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE statut (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE activite ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE centre_de_charge ADD id_responsable_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE centre_de_charge ADD CONSTRAINT FK_B9DD5F996EA32074 FOREIGN KEY (id_responsable_id) REFERENCES employe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_B9DD5F996EA32074 ON centre_de_charge (id_responsable_id)');
        $this->addSql('ALTER TABLE detail_heures ADD statut_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE detail_heures ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE detail_heures ALTER tache_specifique_id TYPE VARCHAR');
        $this->addSql('ALTER TABLE detail_heures ADD CONSTRAINT FK_CC6F9EC6F6203804 FOREIGN KEY (statut_id) REFERENCES statut (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_CC6F9EC6F6203804 ON detail_heures (statut_id)');
        $this->addSql('ALTER TABLE site_tache_specifique ADD CONSTRAINT FK_5E8861C9F6BD1646 FOREIGN KEY (site_id) REFERENCES site (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE site_tache_specifique ADD CONSTRAINT FK_5E8861C98DC5A8C1 FOREIGN KEY (tache_specifique_id) REFERENCES tache_specifique (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_5E8861C9F6BD1646 ON site_tache_specifique (site_id)');
        $this->addSql('CREATE INDEX IDX_5E8861C98DC5A8C1 ON site_tache_specifique (tache_specifique_id)');
        $this->addSql('ALTER TABLE type_heures ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP TABLE statut');
        $this->addSql('ALTER TABLE type_heures ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE site_tache_specifique DROP CONSTRAINT FK_5E8861C9F6BD1646');
        $this->addSql('ALTER TABLE site_tache_specifique DROP CONSTRAINT FK_5E8861C98DC5A8C1');
        $this->addSql('DROP INDEX IDX_5E8861C9F6BD1646');
        $this->addSql('DROP INDEX IDX_5E8861C98DC5A8C1');
        $this->addSql('ALTER TABLE activite ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE centre_de_charge DROP CONSTRAINT FK_B9DD5F996EA32074');
        $this->addSql('DROP INDEX IDX_B9DD5F996EA32074');
        $this->addSql('ALTER TABLE centre_de_charge DROP id_responsable_id');
        $this->addSql('ALTER TABLE detail_heures DROP CONSTRAINT FK_CC6F9EC6F6203804');
        $this->addSql('DROP INDEX IDX_CC6F9EC6F6203804');
        $this->addSql('ALTER TABLE detail_heures DROP statut_id');
        $this->addSql('ALTER TABLE detail_heures ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE detail_heures ALTER tache_specifique_id TYPE VARCHAR(255)');
    }
}
