controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

errors:
    path: /access-denied
    controller: App\Controller\indexController::accessDenied