controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: attribute

errors:
    path: /access-denied
    controller: App\Controller\indexController::accessDenied